spring:
  application:
    name: soup-auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

security:
  jwt:
    secret: ${JWT_SECRET:over-salted-soup}
  access-token:
    expirationMillis: ${ACCESS_TOKEN_EXPIRATION:86400000} #один день
  refresh-token:
    expirationMillis: ${REFRESH_TOKEN_EXPIRATION:2592000000} #15 дней
  password:
    salt: ${PASSWORD_SALT:very-over-salted-soup}
